services:
  nats:
    image: nats:latest
    ports:
      - "4222:4222"
      - "8222:8222"
    command: [ "-js", "-m", "8222" ]

  order-db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 130924
      POSTGRES_DB: order
    ports:
      - "1987:5432"

  payment-db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 130924
      POSTGRES_DB: payment
    ports:
      - "1988:5432"

  order:
    build: ./order
    depends_on:
      - order-db
      - nats
    environment:
      HTTP_SRV_ADDR: :8081
      GRPC_SRV_ADDR: 0.0.0.0:50051
      GRPC_PAYMENT_SRV_ADDR: payment:50052
    ports:
      - "8081:8081"
      - "50051:50051"


  payment:
    build: ./payment
    depends_on:
      - payment-db
      - nats
    environment:
      GRPC_SRV_ADDR: 0.0.0.0:50052
    ports:
      - "8082:8082"
      - "50052:50052"

  notification:
    build: ./notification
    depends_on:
      - nats